import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { KpiCard, SectionCard } from './Cards'

const colors = ['#2563eb', '#22c55e', '#f59e0b', '#ef4444']
const alertStyles = ['border-amber-200 bg-amber-50 text-amber-800', 'border-yellow-200 bg-yellow-50 text-yellow-800', 'border-rose-200 bg-rose-50 text-rose-800']

export default function Dashboard({ analysis }) {
  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-4 md:grid-cols-2">
        {analysis.kpis.map((item) => (
          <KpiCard key={item.title} item={item} />
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <SectionCard title="Spending Breakdown" subtitle="Current month category distribution">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={analysis.chart_data} dataKey="value" nameKey="name" innerRadius={65} outerRadius={110} paddingAngle={4} isAnimationActive>
                    {analysis.chart_data.map((entry, index) => (
                      <Cell key={entry.name} fill={colors[index % colors.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `₹${Number(value).toLocaleString('en-IN')}`} />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className="space-y-3">
              {analysis.chart_data.map((item, index) => (
                <div key={item.name} className="rounded-xl border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <span className="h-3 w-3 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} />
                      <p className="font-semibold text-slate-900">{item.name}</p>
                    </div>
                    <p className="text-sm font-medium text-slate-600">{item.change >= 0 ? '+' : ''}{item.change}%</p>
                  </div>
                  <p className="mt-2 text-sm text-slate-500">₹{item.value.toLocaleString('en-IN')} this month</p>
                </div>
              ))}
            </div>
          </div>
        </SectionCard>

        <SectionCard title="Alerts Panel" subtitle="Real-time signals from the alert agent">
          <div className="space-y-4">
            {analysis.alerts.map((alert, index) => (
              <div key={alert} className={`rounded-xl border p-4 ${alertStyles[index % alertStyles.length]}`}>
                <div className="flex items-center justify-between gap-3">
                  <p className="font-semibold">⚠ {alert}</p>
                  <span className="text-xs font-semibold uppercase tracking-wide">Now</span>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>
      </div>

      <SectionCard title="Recommendations (AI)" subtitle="Personalized actions generated by the advisory agent">
        <div className="grid gap-4 lg:grid-cols-2">
          {analysis.recommendations.map((recommendation) => (
            <div key={recommendation} className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900">
              <p className="font-semibold">✔ {recommendation}</p>
            </div>
          ))}
        </div>
      </SectionCard>

      <SectionCard title="AI Explanation" subtitle="Generative summary built from structured agent output">
        <div className="rounded-xl bg-slate-50 p-5 text-sm leading-7 text-slate-700">{analysis.ai_explanation}</div>
      </SectionCard>
    </div>
  )
}
