import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { MetricCard, Panel, ScoreCard } from './Cards'

const chartColors = ['#22c55e', '#38bdf8', '#a78bfa', '#f97316', '#facc15', '#fb7185', '#94a3b8']

export default function Dashboard({ analysis }) {
  const { spending, financial_health: health, alerts, recommendations, ai_explanation: explanation } = analysis

  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
        <ScoreCard health={health} />
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1">
          <MetricCard
            label="Total spent"
            value={`$${spending.total_spent.toFixed(2)}`}
            caption={`Top category: ${spending.top_category}`}
          />
          <MetricCard
            label="Average transaction"
            value={`$${spending.average_transaction.toFixed(2)}`}
            caption={`${spending.categories.length} tracked categories`}
          />
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <Panel title="Spending Breakdown" subtitle="Category distribution for this month">
          <div className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">
            <div className="h-80">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={spending.categories} dataKey="total" nameKey="category" innerRadius={80} outerRadius={115} paddingAngle={4}>
                    {spending.categories.map((entry, index) => (
                      <Cell key={entry.category} fill={chartColors[index % chartColors.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `$${Number(value).toFixed(2)}`} />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="space-y-3">
              {spending.categories.map((item, index) => (
                <div key={item.category} className="rounded-2xl bg-slate-950/50 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-3">
                      <span className="h-3 w-3 rounded-full" style={{ backgroundColor: chartColors[index % chartColors.length] }} />
                      <p className="font-medium text-white">{item.category}</p>
                    </div>
                    <p className="text-sm text-slate-300">{item.percentage}%</p>
                  </div>
                  <p className="mt-2 text-sm text-slate-400">
                    ${item.total.toFixed(2)} across {item.transaction_count} transactions
                  </p>
                </div>
              ))}
            </div>
          </div>
        </Panel>

        <Panel title="AI Explanation" subtitle="Generative summary based on agent outputs">
          <div className="rounded-2xl bg-slate-950/50 p-5 text-sm leading-7 text-slate-200">{explanation}</div>
        </Panel>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Panel title="Alerts" subtitle="Warnings identified by the alert agent">
          <div className="space-y-4">
            {alerts.map((alert) => (
              <div key={alert.title} className="rounded-2xl border border-amber-400/20 bg-amber-500/10 p-4">
                <div className="flex items-center justify-between gap-3">
                  <p className="font-medium text-white">{alert.title}</p>
                  <span className="rounded-full bg-white/10 px-3 py-1 text-xs uppercase tracking-[0.2em] text-amber-200">
                    {alert.severity}
                  </span>
                </div>
                <p className="mt-3 text-sm leading-6 text-slate-200">{alert.message}</p>
              </div>
            ))}
          </div>
        </Panel>

        <Panel title="Recommendations" subtitle="Actions generated by the advisory agent">
          <div className="space-y-4">
            {recommendations.map((recommendation) => (
              <div key={recommendation.title} className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4">
                <p className="font-medium text-white">{recommendation.title}</p>
                <p className="mt-3 text-sm leading-6 text-slate-200">{recommendation.action}</p>
                <p className="mt-2 text-xs uppercase tracking-[0.2em] text-emerald-200">{recommendation.impact}</p>
              </div>
            ))}
          </div>
        </Panel>
      </div>
    </div>
  )
}
